language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.0

matrix:
 allow_failures:
  - php: 7.0
  - php: 5.6

env:
 matrix:
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql  MOODLE_BRANCH=MOODLE_30_STABLE

before_install:
  # Several tools complain about xdebug slowdown.
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci dev-poet
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:

  # Finally, the standard install step.
  - moodle-plugin-ci install

script:
  - composer validate
  - composer lint
  - php-cs-fixer --dry-run -v fix
  - if [ "$COVERAGE" = true ]; then phpdbg -qrr $(which phpunit) --coverage-clover coverage.clover; fi
  - if [ "$COVERAGE" = false ]; then phpunit; fi

  # This is basically "integration" testing.
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci codechecker --standard poet
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat

after_script:
  - if [ "$COVERAGE" = true ]; then ocular code-coverage:upload --format=php-clover coverage.clover; fi
